// Code generated by command: go run main.go -out ./../copy_amd64.s -stubs ./../stub_amd64.go -pkg asm. DO NOT EDIT.

//go:build amd64 && !purego

package asm

// Copy16 copy and rotate uint64 from `src` to `dst`
//go:noescape
func Copy16(src []uint16, dst []uint16) uint64

// Copy32 copy and rotate uint64 from `src` to `dst`
//go:noescape
func Copy32(src []uint32, dst []uint32) uint64

// Copy64 copy and rotate uint64 from `src` to `dst`
//go:noescape
func Copy64(src []uint64, dst []uint64) uint64
