name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        go: [ '1.16', '1.17.0-beta1' ]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
          stable: '!contains(${{ matrix.go }}, "beta") && !contains(${{ matrix.go }}, "rc")'
          go-version: ${{ matrix.go }}

    - name: Test Unsafe
      run: go test -v ./...

    - name: Test Pure Go
      run: go test -tags="purego" -v ./...

    - name: Test Safe
      run: go test -tags="no_unsafe" -v ./...
