name: Test

on:
  push:
    branches:
      - main 
      - v2
  pull_request:
    branches:  
      - main
      - v2

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.18', '1.19' ]
    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ matrix.go }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
          
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
          stable: '!contains(${{ matrix.go }}, "beta") && !contains(${{ matrix.go }}, "rc")'
          go-version: ${{ matrix.go }}

    - name: Test Unsafe
      run: go test -v ./...

    - name: Test Pure Go
      run: go test -tags="purego" -v ./...

    - name: Test Safe
      run: go test -tags="no_unsafe" -v ./...
